.TH ASGARD 1 "AUGUST 2012" ASGARD "Game Manual"
.SH NAME
.B
asgard
\- classic, video role playing game.
.SH SYNOPSIS
.B asgard
.I script.py

.B asgard
<
.I script.py
.SH DESCRIPTION
.B asgard
is a free software, classic role playing game. Thank you for taking interest in
Asgard. As this project is still in its infancy, this package is intended for
testing, observation and interest piquing. Currently Asgard supports a basic,
bare bones map complete with only a few map objects. You may also click to move
the Character around the map. We encourage you to to compile, run and hack
Asgard.
.SH EXAMPLES
.B asgard /usr/share/asgard/scripts/demo1.py

Load the map from the database onto the screen.

.B asgard /usr/share/asgard/scripts/demo3.py

Load the map from the database onto the screen and do a sloppy pan across the
map in a rectangular motion.
.SH AUTHOR
Written by Russ Adams <russ dot adams at gmail dot com>
    and by Sean Eubanks <seanmeu at gmail dot com>

.SH REPORTING BUGS
Report asgard bugs at <http://bugs.launchpad.net/asgard>.
